import type { NextPage } from 'next';
import Head from 'next/head';
import {
	AboutSection,
	Features,
	LatestNews,
	MainHero,
	PromoBox,
	ReviewsSection,
	TeamSection,
} from '../components';

const Home: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Grace Template Clone - Home</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<MainHero />
			<AboutSection />
			<PromoBox />
			<Features />
			<ReviewsSection />
			<TeamSection />
			<LatestNews />
		</div>
	);
};

export default Home;
